k8s_yaml('kubernetes-allane-leasing-ui.yaml')

docker_build(
  'allane-leasing-ui', '.',
  dockerfile='./Dockerfile-local',
  live_update=[
    # when package.json changes, we need to do a full build
    fall_back_on(['package.json', 'package-lock.json']),
    # Map the local source code into the container under /src
    sync('.', '/src'),
  ]
)

k8s_resource(
  'allane-leasing-ui',
  port_forwards=4200
)
