apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      run: mariadb
  replicas: 1
  
  template:
    metadata:
      labels:
        run: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: rootpass
        - name: MARIADB_DATABASE
          value: pastebin
        - name: MARIADB_USER
          value: dev
        - name: MARIADB_PASSWORD
          value: devpass
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    run: mariadb
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    run: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allane-leasing
  labels:
    app: allane-leasing
spec:
  selector:
    matchLabels:
      app: allane-leasing
  template:
    metadata:
      labels:
        app: allane-leasing
    spec:
      containers:
        - name: allane-leasing
          image: allane-leasing-image
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
          ports:
            - containerPort: 8001
              protocol: TCP
            - containerPort: 5001  # debugger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: allane-leasing-service
  name: allane-leasing-service
spec:
  ports:
  - name: 9001-8001
    port: 9001
    protocol: TCP
    targetPort: 8001
  selector:
    app: allane-leasing
  type: ClusterIP
