
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allane-leasing
  labels:
    app: allane-leasing
spec:
  selector:
    matchLabels:
      app: allane-leasing
  template:
    metadata:
      labels:
        app: allane-leasing
    spec:
      containers:
        - name: allane-leasing
          image: allane-leasing-image
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
          ports:
            - containerPort: 8001
              protocol: TCP
            - containerPort: 5001  # debugger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: allane-leasing-service
  name: allane-leasing-service
spec:
  ports:
  - name: 9001-8001
    port: 9001
    protocol: TCP
    targetPort: 8001
  selector:
    app: allane-leasing
  type: ClusterIP
